package com.frozerain.sdbc.event;

public enum EventType {

    UNKNOWN_EVENT,
    CHAT_INPUT_INTERACTION_EVENT,
    USER_INTERACTION_EVENT,
    MESSAGE_INTERACTION_EVENT,
    VOICE_STATE_UPDATE_EVENT,
    MEMBER_LEAVE_EVENT,
    BUTTON_INTERACTION_EVENT,
    MODAL_SUBMIT_INTERACTION_EVENT,
    SELECT_MENU_INTERACTION_EVENT,
    REACTION_ADD_EVENT,
    REACTION_REMOVE_EVENT,
    MESSAGE_CREATE_EVENT,
    MESSAGE_DELETE_EVENT
}
